# Version: 0.01
FROM ubuntu:14.04
MAINTAINER laichengfeng "15767512424@163.com"
RUN apt-get update && apt-get install -y nginx
RUN echo 'Hi, I am in your container' > /usr/share/nginx/html/index.html
EXPOSE 80
